# site settings
title: 50 Years of Terrorism
subtitle: by Abbet C., Masserey N. & Poussard A.
email:
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
url: "" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"
author:
street_address: 
city: 
state: 
zip_code:
country: 
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/AdaTeamElec/ADA2017-Homeworks

# build settings
markdown: kramdown

sass:
  style: compressed
